
[build]
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"
  # Use standard Python installation, not mise
  PIP_DISABLE_PIP_VERSION_CHECK = "1"
  # Ensure we use the runtime.txt specified version
  PYTHONUNBUFFERED = "1"

[functions]
  included_files = ["netlify/functions/**"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
