[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.10"
  NETLIFY_FUNCTIONS_LOG_LEVEL = "debug"

[functions]
  included_files = ["netlify/functions/**"]

# Python function specific settings
[functions."upload-handler"]
  runtime = "python3.10"

[functions."test-handler"]
  runtime = "python3.10"

[functions."hello"]
  runtime = "python3.10"

# Handle specific SPA routes
[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/reader/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/calibration"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/speed-calibration"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/calibrate"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/oauth/callback"
  to = "/index.html"
  status = 200

# Catch-all for any other routes (but not files or functions)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
