
[build]
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.13"
  # Fallback for mise compatibility
  MISE_PYTHON_VERSION = "3.13"
  # Ensure pip is available
  PIP_DISABLE_PIP_VERSION_CHECK = "1"

[functions]
  included_files = ["netlify/functions/**"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
