
[build]
  functions = ".netlify/functions"

[dev]
  targetPort = 8080
  port = 9999

[[redirects]]
  from = "/.netlify/functions/*"
  to   = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
