
[build]
  functions = "netlify/functions"
  command = "npm run build"

[build.environment]
  # Force use of Ubuntu 20.04 focal build image (doesn't use mise by default)
  NETLIFY_BUILD_IMAGE = "focal"
  NETLIFY_EXPERIMENTAL_BUILD_IMAGE = "focal"
  # Completely disable mise tool manager - ALL methods
  NETLIFY_USE_MISE = "false"
  MISE_INSTALL_PATH = ""
  MISE_DATA_DIR = ""
  MISE_CONFIG_FILE = ""
  MISE_DISABLE = "1"
  MISE_SKIP = "1"
  MISE_EXPERIMENTAL = "0"
  MISE_QUIET = "1"
  # Disable mise Python specifically
  MISE_PYTHON_INSTALL = "false"
  MISE_PYTHON_COMPILE = "false"
  # Override any Python version detection
  PYTHON_VERSION = ""
  NETLIFY_PYTHON_VERSION = ""
  # Bypass any version managers completely
  PYENV_ROOT = ""
  ASDF_DIR = ""
  ASDF_SKIP = "1"
  NODENV_ROOT = ""
  RBENV_ROOT = ""
  # Force use of system Python (focal has 3.8/3.9 available)
  PYTHONPATH = "/usr/bin/python3"
  # Standard Python settings
  PIP_DISABLE_PIP_VERSION_CHECK = "1"
  PYTHONUNBUFFERED = "1"
  # Force clean build
  NETLIFY_CLEAR_CACHE = "true"
  NETLIFY_BUILD_DEBUG = "true"

[functions]
  included_files = ["netlify/functions/**"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
