
[build]
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"
  # Explicitly disable mise to use standard Python
  MISE_INSTALL_PATH = ""
  MISE_DATA_DIR = ""
  # Use standard Python installation
  PIP_DISABLE_PIP_VERSION_CHECK = "1"
  PYTHONUNBUFFERED = "1"
  # Force use of runtime.txt
  NETLIFY_USE_RUNTIME_TXT = "true"

[functions]
  included_files = ["netlify/functions/**"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
