

[build]
  functions = "netlify/functions"
  command = "npm run build"

[build.environment]
  # Force use of Ubuntu 20.04 focal build image (doesn't use mise by default)
  NETLIFY_BUILD_IMAGE = "focal"
  NETLIFY_EXPERIMENTAL_BUILD_IMAGE = "focal"
  # Explicitly disable Netlify's mise integration
  NETLIFY_USE_MISE = "false"
  # Completely disable mise tool manager
  MISE_INSTALL_PATH = ""
  MISE_DATA_DIR = ""
  MISE_CONFIG_FILE = ""
  MISE_DISABLE = "1"
  MISE_SKIP = "1"
  # Bypass any version managers
  PYENV_ROOT = ""
  ASDF_DIR = ""
  ASDF_SKIP = "1"
  # Force specific versions without runtime.txt
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"
  # Standard Python settings
  PIP_DISABLE_PIP_VERSION_CHECK = "1"
  PYTHONUNBUFFERED = "1"
  # Enable build debugging
  NETLIFY_BUILD_DEBUG = "true"

[functions]
  included_files = ["netlify/functions/**"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
