
FROM python:3.13-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Python scripts
COPY . .

# Expose the port
EXPOSE 5001

# Start the server
CMD ["python", "app.py"]
